- hosts: all
  remote_user: root
  roles:
    - role: init
- hosts: etcd
  remote_user: root
  roles:
    - role: etcd
#- hosts: haproxy
#  remote_user: root
#  roles:
#    - role: haproxy
#- hosts: master
#  remote_user: root
#  roles:
#    - role: keepalived
