APIPORT: 6443
MASTERIP: "{{ ansible_facts['default_ipv4']['address'] }}"
MASTERNAME: "{{ inventory_hostname }}"
ETCDCLUSTER: "{% for host in groups['etcd'] %}{{ host }}=https://{{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }}:{{  PERRPORT }}{%- if not loop.last -%},{% endif %}{% endfor %}"
ETCDNODENAME: "{{ inventory_hostname }}"
ETCDCLUSTERTOKEN: etcd-cluster-0
ETCDDATADIR: /var/lib/etcd/
CAPATH: /etc/etcd/ssl/
CONFIGPATH: /etc/etcd/
ETCDCACLUSTER: "{% for host in groups['etcd'] %}\"{{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }}\"{%- if not loop.last -%},{% endif %}{% endfor %}"
