---
    - hosts: haproxy
      vars: 
          AAAA: "{% for host in groups['haproxy'] %}{{ host }} {{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }}:6443{%- if not loop.last -%}\n{% endif %}{% endfor %}"
          BBBB: "{{ inventory_hostname  }}{{ cfsssl }}"
          CCCC: "{% for host in groups['all'] %}{{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }} {{ host }}{% endfor %}"
      tasks:
        - debug: msg="{{ AAAA }}"
        - debug: msg="{{ CCCC }}"
#        - name: scp etcd.tar.gz to dest
#          copy: 'src=1.yml dest=/tmp/2.yml '
#
#        - name: check etcd cluster health
#          shell:  etcdctl --ca-file=/etc/etcd/ssl/ca.pem   --cert-file=/etc/etcd/ssl/etcd.pem   --key-file=/etc/etcd/ssl/etcd-key.pem member list
#          register: result
#          until: result.rc == 0
#          retries: 5
#          delay: 10
