- name: 关闭firewalld NetworkManager dnsmasq - CentOS
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - firewalld
    - NetworkManager
    - dnsmasq
  ignore_errors: True
- name: SELINUX disabled
  selinux: state=disabled
- name: sed selinux config
  lineinfile:
    dest: /etc/selinux/config
    regexp: 'SELINUX=enforcing'
    line: 'SELINUX=disabled'
- name: swap  off
  shell: swapoff -a && sysctl -w vm.swappiness=0 && sed -ri '/^[^#]*swap/s@^@#@' /etc/fstab
- name: 添加EPEL仓库
  yum: name=epel-release state=latest update_cache=yes
- name: install yum util
  yum: name=yum-utils update_cache=yes state=latest
- name: yum-complete-transaction
  shell: yum-complete-transaction --cleanup-only
- name: yum basic util install
  yum:
    name:
      - device-mapper-persistent-data
      - lvm2
      - conntrack-tools
      - nfs-utils
      - ipvsadm
      - unzip
      - net-tools
      - ipset
      - socat
      - libseccomp
      - sysstat
      - conntrack
      - unzip
      - ntp
    state: latest
    update_cache: yes

- name: start ntp
  service: name=ntpd state=restarted enabled=yes

- name: check stat
  shell: ntpstat
  register: result
  until: result.rc == 0
  retries: 5
  delay: 10

