- name: Set timezone
  timezone: name=Asia/Shanghai

- name: 分发modules-load和sysctl的conf
  copy:
    src: files/{{ item.src }}
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'k8s-ipvs.conf', dest: "/etc/modules-load.d/" }
    - { src: 'kubernetes.conf', dest: "/etc/security/limits.d/" }
    - { src: 'k8s.conf', dest: "/etc/sysctl.d/k8s-sysctl.conf" }

- name: enable --now systemd-modules-load
  systemd: name=systemd-modules-load state=started enabled=yes

- name: Set hostname
  hostname: name={{ inventory_hostname }}

